# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964118198715a55dda6b8e616bb37f3495b753e37f4225b1dc4492eb9531163935f784eb57eea79e47515b35142c5c5f007e8c411af0a434e4678e566ec9522b

test:
  secret_key_base: 03502ad6f7824a1b94f29b2398b1da11c077a64c6f9bbaef4f83cc427e02df5b53cf334fc4b7379392d1ea891d8ee268cd9b833f524b186e828a75dc352abae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
